spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: catalog-service
        uri: http://localhost:7070
        predicates:
        - Path=/api/v1/catalogs/**
          
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
