server:
  port: 2022
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:4040/oauth/check_token
    client:
      client-id: myclient
      client-secret: pass123